config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    member do
      post 'comment'
      delete 'comment', to: 'articles#delete_comment'
    end
  end

  devise_for :users

  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id          :bigint           not null, primary key
#  title       :string
#  description :text
#  user_id     :bigint           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Article < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image

  # Validations
  validates :title, presence: true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  content    :text
#  user_id    :bigint
#  article_id :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Comment < ApplicationRecord
  # Associations
  belongs_to :article
  belongs_to :user, optional: true

  # Validations
  validates :content, length: { minimum: 3 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  name                   :string           not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  role                   :integer          default("user")
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associations
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :nullify
  has_one_attached :profile_picture

  # Validations
  validates :name, presence: true

  # 0 = user, 1 = admin
  enum :role, [:user, :admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def authorize_request(kind = nil)
    unless kind.include?(current_user.role)
      redirect_to articles_path, notice: "You are not authorized to perform this action"
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile_picture])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile_picture])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # Role permissions
  before_action :authenticate_user!, except: %i[ index show ]
  before_action only: %i[ new edit update destroy ] do
    authorize_request(["admin"])
  end

  # GET /articles or /articles.json
  def index
    @articles = Article.all.order(created_at: :desc)
  end

  # GET /articles/1 or /articles/1.json
  def show
    @comments = Comment.where(article_id: params[:id]).order(:created_at)
  end

  # POST /articles/1
  def comment
    @comment = current_user.comments.new(comment_params.merge(article_id: params[:id]))

    respond_to do |format|
      if @comment.save
        format.html { redirect_to article_path, notice: "Comment created." }
        format.json { redirect_to article_path(format: :json), status: :created, location: @article }
      else
        format.html { redirect_to article_path, flash: { error: @comment.errors.full_messages }}
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1

  def delete_comment
    @comment = Comment.find(params[:comment_id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to article_path, notice: "Comment deleted." }
      format.json { head :no_content }
    end
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, :user_id, :image)
    end

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def time_passed(time)
    seconds = (Time.now - time).round
    if seconds == 0
      return 'Just now'
    end
    minutes, seconds = seconds.divmod(60)
    hours, minutes = minutes.divmod(60)
    result = ""
    if hours > 0
      result += hours.to_s
      if hours > 1
        result += " hours "
      else
        result += " hour "
      end
    end
    if minutes > 0
      result += minutes.to_s
      if minutes > 1
        result += " minutes "
      else
        result += " minute "
      end
    end
    if seconds > 0
      result += seconds.to_s
      if seconds > 1
        result += " seconds "
      else
        result += " second "
      end
    end
    result += "ago"
  end
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div class="alert alert-danger mt-3">
      <h2 class="alert-heading mb-3"><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, required: true, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control", placeholder: "Image description here...", rows: 5 %>
  </div>

  <div class="mb-3">
    <%= form.label :image, class: "form-label" %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="mb-3 text-center">
    <%= form.submit class:"btn btn-light" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-lg-6">
    <h1>Editing article</h1>
    <%= link_to "Show this picture", @article, class: "link-light" %> | <%= link_to "Back to gallery", articles_path, class: "link-light" %>
    <div class="mb-3">
      <p>Current Image:</p>
      <%= image_tag @article.image, class:"img-fluid" %>
    </div>
    <%= render "form", article: @article %>
  </div>
</div>

app/views/articles/index.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<h1 class="text-center">Gallery</h1>

<% if user_signed_in? %>
  <% if user_signed_in? %>
    <div class="text-center mb-3">
      <%= link_to "Publish Picture", new_article_path, class: "btn btn-light" %>
    </div>
  <% end %>
<% end %>

<div id="articles" class="row gy-3 row-cols-1 row-cols-lg-2">
  <% @articles.each do |article| %>
    <div class="col align-self-center">
      <div class="card">
        <%= image_tag article.image, class:"card-img-top border-bottom" if article.image.attached? %>
        <div class="card-body">
          <h5 class="card-title"><%= article.title %></h5>
          <p class="card-text"><small class="text-body-secondary"><%= article.created_at.strftime("%d - %m - %Y")%></small></p>
          <div class="d-flex align-items-center">
            <% if article.user.profile_picture.attached? %>
              <%= image_tag article.user.profile_picture, class: "img-thumbnail me-3", style: "height: 50px" %>
            <% end %>
            <p class="card-text">Written by <%= article.user.name %></p>
          </div>
        </div>
        <div class="card-footer text-center">
          <%= link_to "Show this picture", article, class: "btn btn-light" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-lg-6">
    <h1>New picture</h1>
    <%= link_to "Back to gallery", articles_path, class: "link-light" %>
    <%= render "form", article: @article %>
  </div>
</div>

app/views/articles/show.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if not flash["error"].nil? %>
  <div class="alert alert-danger" role="alert">
    <h2><%= pluralize(flash["error"].count, "error") %> prohibited this comment from being saved:</h2>

    <ul>
      <% flash["error"].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div id="<%= dom_id @article %>" class="mb-3">
  <h1><%= @article.title %></h1>
  <% if @article.image.attached? %>
    <div class="text-center mb-3">
      <%= image_tag @article.image, class:"img-fluid" %>
    </div>
  <% end %>
  <div class="d-flex align-items-center mb-3">
    <% if @article.user.profile_picture.attached? %>
      <%= image_tag @article.user.profile_picture, class: "img-thumbnail me-3", style: "height: 50px" %>
    <% end %>
    <h6 class="mb-0">Posted by <%= @article.user.name %> <small class="text-body-secondary"><%= @article.created_at.strftime("%d - %m - %Y")%></small></h6>
  </div>

  <p>
    <%= @article.description %>
  </p>

  <p>
    <%= link_to "Back to gallery", articles_path, class: "link-light" %>
  </p>

</div>

<div>
  <h2 class="mb-3">Comments</h2>
  <% unless @comments.empty? %>
    <% @comments.each do |comment| %>
      <div class="card mb-3">
        <div class="card-header d-flex align-items-center">
          <% if comment.user.profile_picture.attached? %>
            <%= image_tag comment.user.profile_picture, class: "img-thumbnail me-3", style: "height: 50px" %>
          <% end %>
          <h5 class="mb-0"><strong><%= comment.user_id.nil? ? 'A deleted user' : User.find(comment.user_id).name %></strong> commented:</h5>
        </div>
        <div class="card-body">
          <p class="card-text"><%= comment.content %></p>
        </div>
        <div class="card-footer d-flex align-items-center">
          <p class="my-0 me-auto">
            <% if (Time.now - comment.created_at).round > 1.day %>
              <%= comment.created_at.strftime("%d - %m - %Y") %>
            <% else %>
              <%= time_passed(comment.created_at) %>
            <% end %>
          </p>
          <% if user_signed_in? %>
            <% if current_user.role == 'admin' || comment.user_id == current_user.id %>
              <%= button_to "Delete this comment", comment_article_path, params: { comment_id: comment }, method: :delete, class: "btn btn-danger" %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="card mb-3">
      <div class="card-body">No one has commented yet</div>
    </div>
  <% end %>
</div>

<%# Comment form %>
<%= form_with model: [@article, @article.comments.build], url: comment_article_path do |form| %>
  <div class="mb-3">
    <%= form.label :content, "Leave a comment", class: "form-label fs-2 fw-medium" %>
    <%= form.text_area :content, class: "form-control", placeholder: "Your comment here...", rows: 5 %>
  </div>

  <div class="text-center mb-3">
    <%= form.submit class: "btn btn-light" %>
  </div>
<% end %>

<%# Admin section %>
<% if user_signed_in? %>
  <% if current_user.role == 'admin' %>
    <div class="card text-center">
      <h5 class="card-header">Admin panel</h5>
      <div class="card-body">
        <div class="d-flex justify-content-evenly">
          <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-light" %>
          <%= button_to "Destroy this article", @article, method: :delete, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-bs-theme="dark">
  <head>
    <title>KariPic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container my-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'KariPic', root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <span class="navbar-text">
          Welcome <strong><%= user_signed_in? ? current_user.name : 'Guest' %></strong>
        </span>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Account
          </a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "dropdown-item" %>
              </li>
              <li class="nav-item">
                <%= link_to "Edit user details", edit_user_registration_path, class: "dropdown-item" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
              </li>
              <li class="nav-item">
                <%= link_to "Register", new_user_registration_path, class: "dropdown-item" %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>